alerts = "configs/esalert.d"
es-addr = "127.0.0.1:9200, 127.0.0.1:9201, 127.0.0.1:9202"
es-user = "elastic"
es-pass = "111111"
log-level = "debug"
log-dir = "logs"
dingding-webhook = ""
force-run = ""