alerts = "configs/esalert.d"
es-addr = "10.41.41.145:9200, 10.41.41.145:9201, 10.41.41.145:9202"
es-user = "elastic"
es-pass = "123456"
log-level = "debug"
log-dir = "logs"
dingding-webhook = ""
force-run = ""